# Import all schemas
from .user import *
from .auth import *
from .branch import *
from .purchase import *
from .recycling import *
from .reward import *
from .waste_type import *
from .admin import *
